version: '2'

services:
  drupal:
    image: drupal:8.8.2
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_DB: drupal
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: user
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
