# create your drupal and postgres config here, based off the last assignment
version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports:
      - '8080:80'
    deploy:
      replicas: 2
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:12.1
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: drupal
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pw
      POSTGRES_USER: user
    volumes:
      - drupal-data:/var/lib/postgresql/data
    secrets:
      - psql_pw

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-data:

secrets:
  psql_pw:
    external: true
